spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatapp
      username: yourUsername
      password: yourPassword

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core: DEBUG

mongo:
  options:
    socketTimeout: 3000
    connectTimeout: 3000
    maxConnectionIdleTime: 60000
    maxWaitTime: 120000
    connectionsPerHost: 100
    threadsAllowedToBlockForConnectionMultiplier: 5
