spring:
  data:
    mongodb:
      host: localhost # MongoDB ?? ????
      port: 27017     # MongoDB ?? ?? ??
      database: chatapp # ??? ?????? ??
      username: yourUsername # MongoDB ??? ?? ???? (?? ??)
      password: yourPassword # MongoDB ??? ?? ???? (?? ??)

# ?? ?? (?? ??)
logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core: DEBUG

# MongoDB ????? ?? ?? (?? ??)
mongo:
  options:
    socketTimeout: 3000 # ?? ???? (???)
    connectTimeout: 3000 # ?? ???? (???)
    maxConnectionIdleTime: 60000 # ?? ?? ?? ?? (???)
    maxWaitTime: 120000 # ?? ?? ?? (???)
    connectionsPerHost: 100 # ???? ?? ?? ?
    threadsAllowedToBlockForConnectionMultiplier: 5 # ??? ??? ? ?? ??? ?
